=== matthewsillence/PhD_data/Cast.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Cast" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Cast">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Identifier" index-key="Identifier " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Identifier " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="SealCast1" index-key="Identifier " primary="no" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACTJkRRcceNSpTQVJ2Z53UuAAAAAAI6V2XSeeNAAACSAAEBAABDAGEA
cwB0AAAAAAAAAMK4FSoaHKVBslgJCYZAO/QHAAAAkyZEUXHHjUqU0FSdmed1LkkA
RAAAAAAAAACsr4A5/ADqSJqeHaKEYEXKBwAAAJMmRFFxx41KlNBUnZnndS5JAGQA
ZQBuAHQAaQBmAGkAZQByAAAAAAAAAHcvOAGguUBPqIPbo3YU5QsHAAAAkyZEUXHH
jUqU0FSdmed1LkwAbwBjAGEAdABpAG8AbgAAAAAAAACtFzCmtpcZRJpOr8xoQJqw
BwAAAJMmRFFxx41KlNBUnZnndS5BAGMAYwBlAHMAcwBpAG8AbgAvAEMAbwBsAGwA
ZQBjAHQAaQBvAG4AIABuAHUAbQBiAGUAcgAAAAAAAADJPa2uWjKjQbakJSP/VVJN
BwAAAJMmRFFxx41KlNBUnZnndS5DAG8AbABvAHUAcgAgADEAAAAAAAAAoN54Hvoz
10e5FmA6aE1x2wcAAACTJkRRcceNSpTQVJ2Z53UuQwBvAGwAbwB1AHIAIAAyAAAA
AAAAAN/X6QRBRs9Pu4A/TScP+fQHAAAAkyZEUXHHjUqU0FSdmed1Lk0AYQB0AGUA
cgBpAGEAbAAAAAAAAAD9UIjZSJiAQaAVUCbc2qxpBwAAAJMmRFFxx41KlNBUnZnn
dS5TAHUAcgBmAGEAYwBlAAAAAAAAAGJ0TTU1AxhEn+MGwOePFq0HAAAAkyZEUXHH
jUqU0FSdmed1LlMAdQByAHIAbwB1AG4AZAAAAAAAAADaZf+iD6AzQJNJn9NM6U0N
BwAAAJMmRFFxx41KlNBUnZnndS5DAG8AbgBkAGkAdABpAG8AbgA6ACAAZgBpAG4A
ZQBuAGUAcwBzAAAAAAAAAGAEj2WWR8BGhgYb/R2wwkIHAAAAkyZEUXHHjUqU0FSd
med1LkMAbwBuAGQAaQB0AGkAbwBuADoAIABjAG8AbQBwAGwAZQB0AGUAbgBlAHMA
cwAAAAAAAADu9K0xLbE3R7c5GYT5Tw0QBwAAAJMmRFFxx41KlNBUnZnndS5DAG8A
dgBlAHIAaQBuAGcAAAAAAAAAYeRmo/feaEW1YVyJMVKuGgcAAACTJkRRcceNSpTQ
VJ2Z53UuTgBvAHQAZQBzAAAAAAAAAPbzxSnZU3hPrmcdY6EpucYHAAAAkyZEUXHH
jUqU0FSdmed1Lk0AeQBJAG0AYQBnAGUAAAAAAAAAbVnQ5Eix8k2DB4qyUi0/PAcA
AACTJkRRcceNSpTQVJ2Z53UuSABlAGkAZwBoAHQAAAAAAAAA9M/kA0KH+UWb1aN3
4bTwbQcAAACTJkRRcceNSpTQVJ2Z53UuVwBpAGQAdABoAAAAAAAAAMth0WL2TudP
tRLL5SUnC7gHAAAAkyZEUXHHjUqU0FSdmed1LkYAaQBnAHUAcgBlACAAbgB1AG0A
YgBlAHIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAADAAAAAAAAAAAAAAAAAAAA
AAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="kyZEUXHHjUqU0FSdmed1Lg==
"/>
<od:tableProperty name="SubdatasheetName" type="10" value="[Auto]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="wrgVKhocpUGyWAkJhkA79A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Identifier" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1950"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="rK+AOfwA6kianh2ihGBFyg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Location" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4305"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="dy84AaC5QE+og9ujdhTlCw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Accession_x002F_Collection_x0020_number" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5355"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="rRcwpraXGUSaTq/MaECasA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Colour_x0020_1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="yT2trloyo0G2pCUj/1VSTQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Colour_x0020_2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="oN54Hvoz10e5FmA6aE1x2w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Material" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="39fpBEFGz0+7gD9NJw/59A==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Surface" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="/VCI2UiYgEGgFVAm3NqsaQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Surround" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="YnRNNTUDGESf4wbA548WrQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Condition_x003A__x0020_fineness" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="2mX/og+gM0CTSZ/TTOlNDQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Condition_x003A__x0020_completeness" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="YASPZZZHwEaGBhv9HbDCQg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Covering" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="7vStMS2xN0e3ORmE+U8NEA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Notes" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5085"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="YeRmo/feaEW1YVyJMVKuGg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MyImage" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2790"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="9vPFKdlTeE+uZx1joSm5xg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Height" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="bVnQ5Eix8k2DB4qyUi0/PA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Width" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="9M/kA0KH+UWb1aN34bTwbQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Figure_x0020_number" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="/OMz0X1jkEKsxmy5Cxc1JQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Cast.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Cast.xsd" generated="2019-05-23T09:30:47">
<Cast>
<ID>24</ID>
<Identifier>Adimarius2</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Collection Douët d&apos;Arcq 6201</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>varnished</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>complete</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>L. Douët d&apos;Arcq, &apos;La Collection des Sceaux&apos;, vol. 2, p. 441, no. 6201.  Original in Arch. de l&apos;Emp. L 361.  &apos;Appendu à une bulle du cardinal en faveur de l&apos;hôpital des Haudriettes, datée de Paris, 18 des calendes de mai de l&apos;an 4 du pontificat de Jean XXIII (14 avril 1415).&apos;</Notes>
<MyImage>Allemanus1AN.jpg</MyImage>
<Height>83</Height>
<Width>58</Width>
<Figure_x0020_number>26</Figure_x0020_number>
</Cast>
<Cast>
<ID>25</ID>
<Identifier>Adimarius3</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Collection Douët d&apos;Arcq 6202</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>varnished</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to legend</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Douët d&apos;Arcq, L., &apos;Collection de Sceaux&apos;, vol. 2, p. 441, no. 6202.  Original held in Arch. de l&apos;Emp. K 53, no. 18 bis.  &apos;Appendu à une bulle du cardinal, datée de Paris, 18 des calendes de mai de l&apos;an 4 du pontificat de Jean XXII (14 avril 1415), vidimant des lettres de Charles VI, datées d&apos;Orléans, avril après Pâques, qui donnent le gouvernement de l&apos;hôpital des Haudriettes au grand aumônier. - Nota.  Il est à remarquer que le cardinal scelle le même jour avec deux sceaux tout à fait différents.&apos;</Notes>
<MyImage>Allemanus2AN.jpg</MyImage>
<Height>80</Height>
<Width>56</Width>
<Figure_x0020_number>27</Figure_x0020_number>
</Cast>
<Cast>
<ID>22</ID>
<Identifier>AigrefeuilleF1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Champagne 1449</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>clear</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Cast from a wax impression in the Archives de la Aube.</Notes>
<MyImage>AigrefeuilleF1AN.jpg</MyImage>
<Height>85</Height>
<Figure_x0020_number>14</Figure_x0020_number>
</Cast>
<Cast>
<ID>23</ID>
<Identifier>AlbretL1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Collection Douët d&apos;Arcq 6209</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>varnished</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>clear</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to legend</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>M. Douët d&apos;Arcq, &apos;La Collection des Sceaux&apos;, vol. 2, pp. 442-443, no. 6209.  Original held in Arch. de l&apos;Emp. L 368.  &apos;Même provenance que le numéro 6206&apos;.</Notes>
<MyImage>AlbretL1AN.jpg</MyImage>
<Height>95</Height>
<Width>62</Width>
<Figure_x0020_number>48</Figure_x0020_number>
</Cast>
<Cast>
<ID>27</ID>
<Identifier>Amboise1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Normandie 2156</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>varnished</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>clear</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Cat. no. 2156, from a detached seal in the Musee de Rouen.</Notes>
<MyImage>AmboiseG3AN.jpg</MyImage>
<Height>85</Height>
<Width>65</Width>
<Figure_x0020_number>66</Figure_x0020_number>
</Cast>
<Cast>
<ID>30</ID>
<Identifier>BarboM1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Champagne 1457</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>complete</Condition_x003A__x0020_completeness>
<Covering>plastic cover</Covering>
<Notes>Held in the Archives Nationales, Champagne no. 1457.  &apos;Sceau en navette, de 93 et 51 mill. sur cordelettes de chanvre.  Cire vermeille dans une cuvette de cire vierge et boîte  de fer blanc.- Arch. de la Marne, G / 404, coll. Roserot nº 346 (incomplet).&apos;</Notes>
<MyImage>BarboM1AN.jpg</MyImage>
<Height>93</Height>
<Width>51</Width>
<Figure_x0020_number>51</Figure_x0020_number>
</Cast>
<Cast>
<ID>31</ID>
<Identifier>BarboM2</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Champagne 1464</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>poor</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>plastic cover</Covering>
<Notes>Held in Archives Nationales Champagne no. 1464.</Notes>
<MyImage>BarboM2AN.jpg</MyImage>
<Width>61</Width>
<Figure_x0020_number>52</Figure_x0020_number>
</Cast>
<Cast>
<ID>32</ID>
<Identifier>BarL1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Champagne 1451</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>clear</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>plastic cover</Covering>
<Notes>Held in Archives Nationales Champagne no. 1451.  &apos;Cardinal-diacre de Sainte-Agathe, “administrator 		perpetuus episcopatus et ducatus Lingonensis” – 1403.
	Fragment d’un sceau en navette, de 85 et 62 mill., sur lacs de soie rouge. Cire vermeille dans une cuvette de cire vierge.- Arch. de la Haute Marne, carton réservé 2, H Val des Ecoliers.&apos;  Inventaire des Sceaux de la Champagne, 1451. Size: 85 x 62.</Notes>
<MyImage>BarL1AN.jpg</MyImage>
<Figure_x0020_number>21</Figure_x0020_number>
</Cast>
<Cast>
<ID>33</ID>
<Identifier>BarL2</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Collection Douët d&apos;Arcq 6199</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>slight damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>plastic cover</Covering>
<Notes>L. Douët d&apos;Arcq, &apos;La Collection des Sceaux&apos;, vol. 2, p. 441, no. 6199.  Original in Arch. de l&apos;Emp.  L 846.  &apos;Appendu à une confirmation des priviléges de la Saint-Chapelle du Palai, datée de Boissy, 5 des nones de novembre, l&apos;an 1er du pontificat d&apos;Alexandre V (1er novembre 1409).&apos;</Notes>
<MyImage>BarL2AN.jpg</MyImage>
<Width>67</Width>
<Figure_x0020_number>22</Figure_x0020_number>
</Cast>
<Cast>
<ID>35</ID>
<Identifier>Bessarion1</Identifier>
<Location>Archives Nationales, Paris</Location>
<Accession_x002F_Collection_x0020_number>Service des Sceaux; SC/Champagne 1462</Accession_x002F_Collection_x0020_number>
<Colour_x0020_1>uncoloured</Colour_x0020_1>
<Colour_x0020_2>uncoloured</Colour_x0020_2>
<Material>plaster</Material>
<Surface>plain</Surface>
<Surround>none</Surround>
<Condition_x003A__x0020_fineness>faint</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>damage to design and legend</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
