=== matthewsillence/PhD_data/Document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Document" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Document">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="DocumentDocument reference" index-key="Document_x0020_reference " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="DocumentIndividuals named on the document" index-key="Individuals_x0020_named_x0020_on_x0020_the_x0020_document " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Location" index-key="Location " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Number of seals and blanks" index-key="Number_x0020_of_x0020_seals_x0020_and_x0020_blanks " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Place" index-key="Place " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Document_x0020_reference " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Year" index-key="Memo_x0020_date " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABgKJ8H9pgAQpv96ri5Q0RKAAAAAKblGvlKWONAAACOAAFEAjBEAG8A
YwB1AG0AZQBuAHQAAAAAAAAAgwc2fonPY0Sn5r9dt7y1XwcAAABgKJ8H9pgAQpv9
6ri5Q0RKSQBEAAAAAAAAAPgP0xcj7fNOiMZRkGxOzfEHAAAAYCifB/aYAEKb/eq4
uUNESkQAbwBjAHUAbQBlAG4AdAAgAHIAZQBmAGUAcgBlAG4AYwBlAAAAAAAAAP7m
wYqsJLhNmJ6K376ku38HAAAAYCifB/aYAEKb/eq4uUNESkwAbwBjAGEAdABpAG8A
bgAAAAAAAACtei0JMWMKRLAIdoo3DnJ1BwAAAGAonwf2mABCm/3quLlDREpEAGUA
dABhAGMAaABlAGQAIABpAG0AcAByAGUAcwBzAGkAbwBuACAAbwByACAAYwBhAHMA
dAAAAAAAAABIKSO2MQvLR5O7E9by3ewjBwAAAGAonwf2mABCm/3quLlDREpOAHUA
bQBiAGUAcgAgAG8AZgAgAHMAZQBhAGwAcwAgAGEAbgBkACAAYgBsAGEAbgBrAHMA
AAAAAAAASH/LySYIG0yU3NmkhUGlqwcAAABgKJ8H9pgAQpv96ri5Q0RKUwBlAGEA
bABpAG4AZwAgAGMAbABhAHUAcwBlAAAAAAAAAAtg0I7ghzJLjjaEALcYtT8HAAAA
YCifB/aYAEKb/eq4uUNESkQAYQB0AGUAIAAoAE8AbABkACAAUwB0AHkAbABlACkA
AAAAAAAA1ySdOncv4UKrIUGN2TKIwwcAAABgKJ8H9pgAQpv96ri5Q0RKRABhAHQA
ZQAgACgATgBlAHcAIABTAHQAeQBsAGUAKQAAAAAAAAD6zXWNyuHjS7OFdht2vh50
BwAAAGAonwf2mABCm/3quLlDREpNAGUAbQBvACAAZABhAHQAZQAAAAAAAACbMrtE
RLfrT7dOvHkoOG6ZBwAAAGAonwf2mABCm/3quLlDREpEAG8AYwB1AG0AZQBuAHQA
IABuAG8AdABlAHMAAAAAAAAA4ioEE4NqTk+DvX5O3DMTOwcAAABgKJ8H9pgAQpv9
6ri5Q0RKUABsAGEAYwBlAAAAAAAAANnCSNr2GkNBiJCSKXnWHXsHAAAAYCifB/aY
AEKb/eq4uUNESlMAZQBhAGwAIABvAHcAbgBlAHIALwB1AHMAZQByAAAAAAAAACOy
lE0gsQtHnh1nfcKf8foHAAAAYCifB/aYAEKb/eq4uUNESkQAYQB0AGUAIAB2AGkA
ZQB3AGUAZAAAAAAAAACHO8NvXzzcQK6JYPB++VAiBwAAAGAonwf2mABCm/3quLlD
REpEAGEAdABlACAAYwBoAGUAYwBrAGUAZAAAAAAAAADBIclWgsx+Tq3Td+de3Iqv
BwAAAGAonwf2mABCm/3quLlDREpJAG4AZABpAHYAaQBkAHUAYQBsAHMAIABuAGEA
bQBlAGQAIABvAG4AIAB0AGgAZQAgAGQAbwBjAHUAbQBlAG4AdAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAMAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="SubdatasheetName" type="10" value="[None]"/>
<od:tableProperty name="GUID" type="9" value="YCifB/aYAEKb/eq4uUNESg==
"/>
<od:tableProperty name="FrozenColumns" type="3" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="615"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="gwc2fonPY0Sn5r9dt7y1Xw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Document_x0020_reference" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4965"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="+A/TFyPt806IxlGQbE7N8Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Location" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3105"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="/ubBiqwkuE2YnorfvqS7fw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Detached_x0020_impression_x0020_or_x0020_cast" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2820"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="rXotCTFjCkSwCHaKNw5ydQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Number_x0020_of_x0020_seals_x0020_and_x0020_blanks" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2775"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="SCkjtjELy0eTuxPW8t3sIw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Sealing_x0020_clause" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2145"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="SH/LySYIG0yU3NmkhUGlqw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Date_x0020__x0028_Old_x0020_Style_x0029_" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2265"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="C2DQjuCHMkuONoQAtxi1Pw==
"/>
<od:fieldProperty name="Format" type="10" value="Long Date"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Memo_x0020_date" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4305"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="+s11jcrh40uzhXYbdr4edA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Document_x0020_notes" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="13455"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="mzK7RES360+3Trx5KDhumQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Place" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="4ioEE4NqTk+DvX5O3DMTOw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Seal_x0020_owner_x002F_user" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2580"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="2cJI2vYaQ0GIkJIpedYdew==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Date_x0020_viewed" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="I7KUTSCxC0eeHWd9wp/x+g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Date_x0020_checked" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="14"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="General Date"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="hzvDb1883ECuiWDwfvlQIg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Individuals_x0020_named_x0020_on_x0020_the_x0020_document" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="12270"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="GUID" type="9" value="wSHJVoLMfk6t03fnXtyKrw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Document.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Document.xsd" generated="2019-05-23T09:31:01">
<Document>
<ID>94</ID>
<Document_x0020_reference>AA. Arm. D. 29</Document_x0020_reference>
<Location>Vatican Archive</Location>
<Detached_x0020_impression_x0020_or_x0020_cast>attached impression</Detached_x0020_impression_x0020_or_x0020_cast>
<Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>6; 7 lost</Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>
<Sealing_x0020_clause>Sealing clause</Sealing_x0020_clause>
<Date_x0020__x0028_Old_x0020_Style_x0029_>1378-08-09T00:00:00</Date_x0020__x0028_Old_x0020_Style_x0029_>
<Memo_x0020_date>1378 9 August</Memo_x0020_date>
<Document_x0020_notes>Letters patent of thirteen cardinals at Anagni declaring Pope Urban VI an antipope and schismatic.

6 fragmentary seals attached to document, 7 lost.  Document compiled on the death of Pope Gregory.

Index entries:

ASV Indice 57, fol. 102r-102v: belonging to set of ‘Litterae patentes tresdecim Cardinalium qui Anagnae ex / istentes Vrbanum sextum decla[m]is intrusum Antipapam &amp; schismaticum et sunt plures eiusdem tenoris.’

Indice 1001, p. 241: ‘(AA. Arm. D, Caps. I, &quot;Diversa in schismate Clem. 7 et Urb. VI&quot;, fasc. 2, n. 3) «Littere / patentes tresdecim, antipapam cardinalium qui Anagniae existentes Urbanum sextum declara / runt intrusum, antipapam &amp; schismaticum.  Et sunt plures eiusdem tenoris.» Membr. / m. 0,373 (più la plica di m. 0,050) x 0,555.  Literae patentes tresdecim cardinalium / ut supra, sub eorum sigillis.  «Universis Xpi fidelibus . . . Exigit sancte et catho / lice fidei puritas . . . Datum Anagnie . . . Anno a nativitate dni Millo Trecentesi / mo Septuagesimo octavo, die nona mensis Augusti prime Indictionis . . . » / 
Sigillata con tredici sigilli in cera rossa, appesi a coda doppia con striscie dip erg. / 
1º Frammento di sigillo ogivale, in cui si veggono soltanto le teste di tre figure di santi, / nel secondo ordine. / 
2º Ogivale alquanto mutilo nei suoi angoli e negli orli.  Tipo, edicola gotica con figu / ra della Madonna col Bambino, nell’estremità superiore.  Tre figure di santi (delle qua / li quella di mezzo, verosimilmente rappresenta il protomartire S. Stefano), nel centro. / Figura di vescovo genuflesso ed orante, fra due stemmi, dei quali ne rimane uno sol / tanto, e questo consiste in un lambello e tre stele .  Questo sigillo appartiene al card. / Guglielmo di Agrifolio, giuniore del titolo di S. Stefano al Monte Celio. / 
3º Frammento di sigillo ogivale, in cui non rimane alter che una figura di vescovo oran / te e genuflesso, nell’estremità inferiore.  Della leggenda non rimangono che queste poche / lettere, e cioè : « . . . . RATI SCE CECI[lie] . . . .» (Betranti (sic) S. Cecilie . . .). / 
4º Non rimane che la striscia dip erg. Con qualche avanzo di cera rossa.
5º “		“		“		“
6º”		“		“		“
7º Striscia di perg. nella quale rimane attaccato un piccolo frammento di cera rossa. / 
8º Non rimane che la striscia di pergamena.
9º Striscia di perg. nella rimane aderente un pezzo di sigillo ogivale , in cui si vede qual / che avanzo di una figura di vescovo genuflesso, ed uno stemma un poco mutilo.  Della / leggenda non rimangono che queste poche lettere : « . . . SCI . . . .». / 
10º Altro non rimane che la striscia di perg. on qualche avanzo di cera rossa.
11º	“
12º Striscia di perg. con un frammento di sigillo, malamente impresso di modo che nulla / vi si distingue. / 
13. Striscia di pergamena. / 
Con alcune macchie prodotte dalla muffa.’</Document_x0020_notes>
<Place>College of Cardinals, Rome</Place>
<Date_x0020_viewed>10/10/2006</Date_x0020_viewed>
<Date_x0020_checked>2007-09-18T00:00:00</Date_x0020_checked>
<Individuals_x0020_named_x0020_on_x0020_the_x0020_document>Gullielmus
Bertrandus</Individuals_x0020_named_x0020_on_x0020_the_x0020_document>
</Document>
<Document>
<ID>101</ID>
<Document_x0020_reference>AA. Arm. D. 32</Document_x0020_reference>
<Location>Vatican Archive</Location>
<Detached_x0020_impression_x0020_or_x0020_cast>attached impression</Detached_x0020_impression_x0020_or_x0020_cast>
<Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>5; 8 lost</Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>
<Sealing_x0020_clause>Sealing clause</Sealing_x0020_clause>
<Date_x0020__x0028_Old_x0020_Style_x0029_>1378-08-09T00:00:00</Date_x0020__x0028_Old_x0020_Style_x0029_>
<Memo_x0020_date>1378 9 August</Memo_x0020_date>
<Document_x0020_notes>Letters patent of thirteen cardinals at Anagni declaring Pope Urban VI an antipope and schismatic.

Sede vacante document, possibly sealed by thirteen cardinals, though some fragments appear to be episcopal seals.

ASV Indice 57, fol. 102r-102v: belonging to set of &apos;Litterae patentes tresdecim Cardinalium qui Anagnae ex / istentes Vrbanum sextum decla[m]is intrusum Antipapam &amp; schismaticum et sunt plures eiusdem tenoris.&apos;</Document_x0020_notes>
<Place>Anagni</Place>
<Seal_x0020_owner_x002F_user>Lagier, Bertrando</Seal_x0020_owner_x002F_user>
<Date_x0020_viewed>31/10/2006</Date_x0020_viewed>
<Date_x0020_checked>2007-09-18T00:00:00</Date_x0020_checked>
<Individuals_x0020_named_x0020_on_x0020_the_x0020_document>John?; Guillaume Aigrefeuille; Betrand Lagier; Roberto di Ginevra; Hugues de Montalais; Guido di Malesset; Jean de la Grange; Pierre de Sortenac; Gerard du Puy; Guillaume Noellet; Pierre Flandin; Pierre de Vergne; Pietro di Luna;</Individuals_x0020_named_x0020_on_x0020_the_x0020_document>
</Document>
<Document>
<ID>26</ID>
<Document_x0020_reference>AA. Arm. D. 34</Document_x0020_reference>
<Location>Vatican Archive</Location>
<Detached_x0020_impression_x0020_or_x0020_cast>attached impression</Detached_x0020_impression_x0020_or_x0020_cast>
<Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>1; 12 lost</Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>
<Sealing_x0020_clause>Illegible</Sealing_x0020_clause>
<Date_x0020__x0028_Old_x0020_Style_x0029_>1378-08-09T00:00:00</Date_x0020__x0028_Old_x0020_Style_x0029_>
<Memo_x0020_date>1378 9 August</Memo_x0020_date>
<Document_x0020_notes>Letters patent of thirteen cardinals at Anagni declaring Pope Urban VI an antipope and schismatic.

Badly conserved and showing signs of fragmentation.  Parts illegible.  Cord tie holes suggest that 13 seals were originally appended to the document.

ASV Indice 57, fol. 102r-102v: belonging to set of &apos;Litterae patentes tresdecim Cardinalium qui Anagnae ex / istentes Vrbanum sextum decla[m]is intrusum Antipapam &amp; schismaticum et sunt plures eiusdem tenoris.&apos;</Document_x0020_notes>
<Place>Anagni</Place>
<Seal_x0020_owner_x002F_user>Malesset, Guido di</Seal_x0020_owner_x002F_user>
<Date_x0020_viewed>27/10/2006</Date_x0020_viewed>
<Date_x0020_checked>2007-09-18T00:00:00</Date_x0020_checked>
</Document>
<Document>
<ID>103</ID>
<Document_x0020_reference>AA. Arm. D. 37</Document_x0020_reference>
<Location>Vatican Archive</Location>
<Detached_x0020_impression_x0020_or_x0020_cast>attached impression</Detached_x0020_impression_x0020_or_x0020_cast>
<Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>2, 10 lost, 1 detached</Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>
<Sealing_x0020_clause>Sealing clause</Sealing_x0020_clause>
<Date_x0020__x0028_Old_x0020_Style_x0029_>1378-08-09T00:00:00</Date_x0020__x0028_Old_x0020_Style_x0029_>
<Memo_x0020_date>1378 9 August</Memo_x0020_date>
<Document_x0020_notes>Letters patent of thirteen cardinals at Anagni declaring Pope Urban VI an antipope and schismatic.

Document on the election of Urban VI, signed by 13 cardinals.  2 seals identified (1 present, 1 detached), a 3rd present unidentified in Sella and Laurent.

ASV Indice 57, fol. 102v: &apos;Hortatariae Cardinalium Anagniae existentium ad Vrbanum VI vt Pontificatum deponat, &amp; poenitentiam agat.&apos;</Document_x0020_notes>
<Place>Anagni</Place>
<Seal_x0020_owner_x002F_user>Aigrefeuille, Guillaume</Seal_x0020_owner_x002F_user>
<Date_x0020_viewed>27/10/2006</Date_x0020_viewed>
<Date_x0020_checked>2007-09-18T00:00:00</Date_x0020_checked>
<Individuals_x0020_named_x0020_on_x0020_the_x0020_document>Guillemus; Bertrandus; Robertus; Hugo; Johannes; Petrus; Gerardus; Petrus;</Individuals_x0020_named_x0020_on_x0020_the_x0020_document>
</Document>
<Document>
<ID>104</ID>
<Document_x0020_reference>AA. Arm. D. 38</Document_x0020_reference>
<Location>Vatican Archive</Location>
<Detached_x0020_impression_x0020_or_x0020_cast>detached impression</Detached_x0020_impression_x0020_or_x0020_cast>
<Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>unknown; 1 detached</Number_x0020_of_x0020_seals_x0020_and_x0020_blanks>
<Sealing_x0020_clause>Sealing clause</Sealing_x0020_clause>
<Date_x0020__x0028_Old_x0020_Style_x0029_>1378-10-07T00:00:00</Date_x0020__x0028_Old_x0020_Style_x0029_>
<Memo_x0020_date>1378 7 October (after assumption of Clement VII (antipapa))</Memo_x0020_date>
<Document_x0020_notes>Certification and publication of the election of Pope Clement VII by twelve cardinals.

Document witnessed &apos;sub sigillis priorum n[ost]ri Collegii vii k[a]l[ens] Octobris post assumptione prefati domini n[ost]ri Clementis&apos;.

ASV Indice 57, fol. 102v: &apos;P[on]tificatio et [ . . ]bb[ . . . . . ] electionis Clementis Septimi facto Fundis per Cardinales ibi existentes.&apos;
