=== matthewsillence/PhD_data/Effigy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Effigy" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Effigy">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Identifier" index-key="Identifier " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADGq0RBB4kQRKv/81crzLBqAAAAAGvaFGn0VeNAAACOAAEAAABFAGYA
ZgBpAGcAeQAAAAAAAAAroxt4zKk7T78z2y6MfwvGBwAAAMarREEHiRBEq//zVyvM
sGpJAEQAAAAAAAAAa/8KdAgqpU6LiF14/S6pVwcAAADGq0RBB4kQRKv/81crzLBq
SQBkAGUAbgB0AGkAZgBpAGUAcgAAAAAAAACCclMqSIVCQ7guxlyXdgPFBwAAAMar
REEHiRBEq//zVyvMsGpTAHQAYQBuAGMAZQAAAAAAAACwIpHf1y2XSYdklwQ4fs1I
BwAAAMarREEHiRBEq//zVyvMsGpBAHIAbQAgAGcAZQBzAHQAdQByAGUAAAAAAAAA
yECEYDLZLUi2QjMTgYTVWwcAAADGq0RBB4kQRKv/81crzLBqSABlAGEAZAAgAGcA
ZQBzAHQAdQByAGUAAAAAAAAAoxswUhErP06UBuuN1S4BqQcAAADGq0RBB4kQRKv/
81crzLBqQQB0AHQAcgBpAGIAdQB0AGUAMQAAAAAAAAABfWapftdeTrRiwVrkQC/W
BwAAAMarREEHiRBEq//zVyvMsGpBAHQAdAByAGkAYgB1AHQAZQAyAAAAAAAAALKA
Bc1lHEpBjLAeox3iHOgHAAAAxqtEQQeJEESr//NXK8ywakgAZQBhAGQAIABjAG8A
dgBlAHIAaQBuAGcAAAAAAAAA0a3WyiFQyUuW/zhIGQTg1QcAAADGq0RBB4kQRKv/
81crzLBqVgBlAHMAdABtAGUAbgB0AHMAAAAAAAAAhCKHiElp0UmNFK/MkMbZRAcA
AADGq0RBB4kQRKv/81crzLBqRABpAHIAZQBjAHQAaQBvAG4AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAwAAAADAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="xqtEQQeJEESr//NXK8ywag==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="K6MbeMypO0+/M9sujH8Lxg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Identifier" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="a/8KdAgqpU6LiF14/S6pVw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Stance" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="gnJTKkiFQkO4LsZcl3YDxQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Arm_x0020_gesture" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3090"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="sCKR39ctl0mHZJcEOH7NSA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Head_x0020_gesture" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="yECEYDLZLUi2QjMTgYTVWw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Attribute1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="oxswUhErP06UBuuN1S4BqQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Attribute2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="AX1mqX7XXk60YsFa5EAv1g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Head_x0020_covering" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="soAFzWUcSkGMsB6jHeIc6A==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Vestments" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="0a3WyiFQyUuW/zhIGQTg1Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Direction" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2565"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="hCKHiElp0UmNFK/MkMbZRA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Effigy.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Effigy.xsd" generated="2019-05-23T09:31:22">
<Effigy>
<ID>1</ID>
<Identifier>AigrefeuilleG1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-right</Direction>
</Effigy>
<Effigy>
<ID>2</ID>
<Identifier>Albergati1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, holding book</Arm_x0020_gesture>
<Head_x0020_gesture>downwards</Head_x0020_gesture>
<Attribute1>book</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>none</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>right</Direction>
</Effigy>
<Effigy>
<ID>3</ID>
<Identifier>Correr1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>left</Direction>
</Effigy>
<Effigy>
<ID>4</ID>
<Identifier>Adimarius3</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>crosier</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>5</ID>
<Identifier>Adimarius2</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>6</ID>
<Identifier>AigrefeuilleF1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>7</ID>
<Identifier>AlbretL1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>forwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>full face</Direction>
</Effigy>
<Effigy>
<ID>8</ID>
<Identifier>Amboise1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>forwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>none</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>9</ID>
<Identifier>BarboM1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>forwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>full face</Direction>
</Effigy>
<Effigy>
<ID>10</ID>
<Identifier>BarL1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>11</ID>
<Identifier>BarL2</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>12</ID>
<Identifier>Bessarion1</Identifier>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
</Effigy>
<Effigy>
<ID>13</ID>
<Identifier>Borsano1</Identifier>
<Stance>kneeling</Stance>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Direction>left</Direction>
</Effigy>
<Effigy>
<ID>14</ID>
<Identifier>BoulogneG1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>15</ID>
<Identifier>Brunhiac1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>none</Head_x0020_covering>
<Vestments>chasuble?</Vestments>
<Direction>right</Direction>
</Effigy>
<Effigy>
<ID>16</ID>
<Identifier>Calleville1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>17</ID>
<Identifier>CampeggioL2</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>18</ID>
<Identifier>CapranicaA1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-right</Direction>
</Effigy>
<Effigy>
<ID>19</ID>
<Identifier>Carvajal1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>none</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>full face</Direction>
</Effigy>
<Effigy>
<ID>20</ID>
<Identifier>CastiglioneB1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>left</Direction>
</Effigy>
<Effigy>
<ID>21</ID>
<Identifier>Challant1</Identifier>
</Effigy>
<Effigy>
<ID>22</ID>
<Identifier>Chanac1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>23</ID>
<Identifier>ClermontF1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>indistinct</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>left</Direction>
</Effigy>
<Effigy>
<ID>24</ID>
<Identifier>CoetivyA1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>forwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>full face</Direction>
</Effigy>
<Effigy>
<ID>25</ID>
<Identifier>EstoutevilleG2</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>forwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>full face</Direction>
</Effigy>
<Effigy>
<ID>26</ID>
<Identifier>FieschiL1</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
<Head_x0020_gesture>upwards</Head_x0020_gesture>
<Attribute1>none</Attribute1>
<Attribute2>none</Attribute2>
<Head_x0020_covering>mitre</Head_x0020_covering>
<Vestments>chasuble</Vestments>
<Direction>half-left</Direction>
</Effigy>
<Effigy>
<ID>27</ID>
<Identifier>FoixP2</Identifier>
<Stance>kneeling</Stance>
<Arm_x0020_gesture>hands raised, held together</Arm_x0020_gesture>
