=== matthewsillence/PhD_data/Heraldry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Heraldry" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Heraldry">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Identifier" index-key="Identifier " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Number" index-key="Number " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAD+kw4YIOwDQ5NPaNvJq9JiAAAAAAiKRtFxZ+NAAAAAAPgDAABIAGUA
cgBhAGwAZAByAHkAAAAAAAAA2qIS4z1sBEWu2aEdJOuZAgcAAAD+kw4YIOwDQ5NP
aNvJq9JiQwBhAHQAZQBnAG8AcgB5AAAAAAAAABxkwU2svTxJo9E6ifjTvRkHAAAA
/pMOGCDsA0OTT2jbyavSYkkARAAAAAAAAACL33twbhmlQYT+FzH67IEvBwAAAP6T
Dhgg7ANDk09o28mr0mJJAGQAZQBuAHQAaQBmAGkAZQByAAAAAAAAAL2d+kdmBLlK
uuewdsHUvMsHAAAA/pMOGCDsA0OTT2jbyavSYlMAaABpAGUAbABkACAAdAB5AHAA
ZQAAAAAAAAA2Nahm2fNhQbv5VA43gIRMBwAAAP6TDhgg7ANDk09o28mr0mJTAHUA
cABwAG8AcgB0AHMAAAAAAAAAhqEtEFmj/0KKPCTxzAmDXAcAAAD+kw4YIOwDQ5NP
aNvJq9JiUwB1AHAAcABvAHIAdABlAHIAcwAAAAAAAABK9ZSr7qjUTpAUfX8jYXcp
BwAAAP6TDhgg7ANDk09o28mr0mJTAHUAcgByAG8AdQBuAGQAAAAAAAAA07lZ5qeC
2E+QC6F0UNQ6bAcAAAD+kw4YIOwDQ5NPaNvJq9JiQQBjAGgAaQBlAHYAZQBtAGUA
bgB0AAAAAAAAAC7RfScn3INKiyYQ1TKrMN8HAAAA/pMOGCDsA0OTT2jbyavSYk4A
dQBtAGIAZQByAAAAAAAAAKzawPa2Pm1Jjj5lc0bVDvAHAAAA/pMOGCDsA0OTT2jb
yavSYkkAbgBzAGkAZwBuAGkAYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAQA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="/pMOGCDsA0OTT2jbyavSYg==
"/>
<od:tableProperty name="OrderBy" type="12" value="Heraldry.Category"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="HGTBTay9PEmj0TqJ+NO9GQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Identifier" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="i997cG4ZpUGE/hcx+uyBLw==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Category" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3495"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="2qIS4z1sBEWu2aEdJOuZAg==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Shield_x0020_type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="RowSource" type="12" value="&quot;plain&quot;;&quot;scrolled&quot;;&quot;&quot;"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="1440"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="vZ36R2YEuUq657B2wdS8yw==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Supports" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2115"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="NjWoZtnzYUG7+VQON4CETA==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Supporters" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="hqEtEFmj/0KKPCTxzAmDXA==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Surround" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="SvWUq+6o1E6QFH1/I2F3KQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Achievement" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3405"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="RowSource" type="12" value="&quot;cardinal&apos;s hat&quot;;&quot;cardinal&apos;s hat with straight cords&quot;;&quot;cardinal&apos;s hat with looped cords&quot;;&quot;&quot;"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="1440"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="07lZ5qeC2E+QC6F0UNQ6bA==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Number" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="LtF9Jyfcg0qLJhDVMqsw3w==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Insignia" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="RowSource" type="12" value="&quot;cross-staff&quot;;&quot;crosier&quot;"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="1440"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="rNrA9rY+bUmOPmVzRtUO8A==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Heraldry.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Heraldry.xsd" generated="2019-05-23T09:31:35">
<Heraldry>
<ID>45</ID>
<Identifier>LanghamS1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>65</ID>
<Identifier>Puy1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>62</ID>
<Identifier>Pierre2</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>72</ID>
<Identifier>Vergne1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>39</ID>
<Identifier>Grimaldi1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>55</ID>
<Identifier>Montalais1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Surround>structural</Surround>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>63</ID>
<Identifier>PierreCosmedin1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>23</ID>
<Identifier>Chanac1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>70</ID>
<Identifier>Sortenac1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>79</ID>
<Identifier>Borsano1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
</Heraldry>
<Heraldry>
<ID>3</ID>
<Identifier>AigrefeuilleG1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>48</ID>
<Identifier>Luna2</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>89</ID>
<Identifier>SoderiniF1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Surround>cornucopiae</Surround>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
</Heraldry>
<Heraldry>
<ID>83</ID>
<Identifier>LangM1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Insignia>cross-staff</Insignia>
</Heraldry>
<Heraldry>
<ID>50</ID>
<Identifier>Malesset1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>12</ID>
<Identifier>BoulogneG1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>40</ID>
<Identifier>Gros1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>81</ID>
<Identifier>CorsiniP1</Identifier>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
</Heraldry>
<Heraldry>
<ID>5</ID>
<Identifier>Amboise1</Identifier>
<Category>ecclesiastical and personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
<Insignia>cross-staff</Insignia>
</Heraldry>
<Heraldry>
<ID>16</ID>
<Identifier>KempJ1</Identifier>
<Category>ecclesiastical and personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>27</ID>
<Identifier>Correr1</Identifier>
<Category>ecclesiastical/personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>37</ID>
<Identifier>GonzagaF1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>36</ID>
<Identifier>GonzagaE1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Surround>decorative corbels</Surround>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>35</ID>
<Identifier>Givry1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>44</ID>
<Identifier>Lagier2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>43</ID>
<Identifier>Lagier1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>42</ID>
<Identifier>Jean1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>38</ID>
<Identifier>Grange2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>28</ID>
<Identifier>EpinayA1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>1</Number>
<Insignia>cross-staff</Insignia>
</Heraldry>
<Heraldry>
<ID>15</ID>
<Identifier>CampeggioL1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>17</ID>
<Identifier>CapranicaA1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>19</ID>
<Identifier>Carvajal1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>20</ID>
<Identifier>CarvajalB1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
<Insignia>cross-staff</Insignia>
</Heraldry>
<Heraldry>
<ID>21</ID>
<Identifier>CastiglioneB1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>11</ID>
<Identifier>Bessarion1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>31</ID>
<Identifier>FieschiL1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>9</ID>
<Identifier>BarL1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>34</ID>
<Identifier>FonsecaP1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>29</ID>
<Identifier>EstoutevilleG1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>53</ID>
<Identifier>MediciG2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Supports>structural</Supports>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
<Insignia>cross-staff</Insignia>
</Heraldry>
<Heraldry>
<ID>30</ID>
<Identifier>EstoutevilleG2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>1</ID>
<Identifier>Adimarius3</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>32</ID>
<Identifier>FieschiN1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>33</ID>
<Identifier>FoixP2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>2</Number>
</Heraldry>
<Heraldry>
<ID>24</ID>
<Identifier>CiboI1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Supports>profile heads</Supports>
<Surround>profile head</Surround>
<Achievement>cardinal&apos;s hat with looped cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>68</ID>
<Identifier>RovereG2</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
<Achievement>cardinal&apos;s hat with straight cords</Achievement>
<Number>1</Number>
</Heraldry>
<Heraldry>
<ID>2</ID>
<Identifier>AigrefeuilleF1</Identifier>
<Category>personal</Category>
<Shield_x0020_type>plain</Shield_x0020_type>
