=== matthewsillence/PhD_data/Matrix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Matrix" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Matrix">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Identifier" index-key="Identifier " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Identifier " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="SealMatrix" index-key="Identifier " primary="no" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADZ+CJnGAa2RZs+1Bl+xYuvAAAAACz0/DPVeeNAAACSAAEAAABNAGEA
dAByAGkAeAAAAAAAAAC15HQO1N/KRr6+fPgwovn7BwAAANn4ImcYBrZFmz7UGX7F
i69JAEQAAAAAAAAAuqcKM/UJrEm+p/y9pC/ZfgcAAADZ+CJnGAa2RZs+1Bl+xYuv
SQBkAGUAbgB0AGkAZgBpAGUAcgAAAAAAAABKVnj6hZy6TJVOS7LxriopBwAAANn4
ImcYBrZFmz7UGX7Fi69MAG8AYwBhAHQAaQBvAG4AAAAAAAAAOXpq8nYWT0WgFrSr
U1MJuwcAAADZ+CJnGAa2RZs+1Bl+xYuvQwBvAGwAbABlAGMAdABpAG8AbgAvAEEA
YwBjAGUAcwBzAGkAbwBuACAAbgB1AG0AYgBlAHIAAAAAAAAAUU6UShKI8UKkUm5P
HnaeIQcAAADZ+CJnGAa2RZs+1Bl+xYuvTQBhAHQAZQByAGkAYQBsAAAAAAAAADRg
qZFSFlFFn3ILpV1EadMHAAAA2fgiZxgGtkWbPtQZfsWLr1MAdQByAGYAYQBjAGUA
AAAAAAAAAcJa+F3/dEOWRupa6yl8OAcAAADZ+CJnGAa2RZs+1Bl+xYuvQwBvAG4A
ZABpAHQAaQBvAG4AOgAgAGYAaQBuAGUAbgBlAHMAcwAAAAAAAADzeCpX88aRQLMI
I0GgvtF4BwAAANn4ImcYBrZFmz7UGX7Fi69DAG8AbgBkAGkAdABpAG8AbgA6ACAA
YwBvAG0AcABsAGUAdABlAG4AZQBzAHMAAAAAAAAAUUIzEc+7MUWCTH+8D5v4cAcA
AADZ+CJnGAa2RZs+1Bl+xYuvQwBvAHYAZQByAGkAbgBnAAAAAAAAAFCPpYaoN4lJ
lw6HxuNVijoHAAAA2fgiZxgGtkWbPtQZfsWLr04AbwB0AGUAcwAAAAAAAACnsz3n
3BHNQ7D5n9SqTbEgBwAAANn4ImcYBrZFmz7UGX7Fi69NAHkASQBtAGEAZwBlAAAA
AAAAAJNWISXdhJlOv2pViUp5FykHAAAA2fgiZxgGtkWbPtQZfsWLr0gAZQBpAGcA
aAB0AAAAAAAAAN37QyTHAtVHufy4GMz+UwgHAAAA2fgiZxgGtkWbPtQZfsWLr1cA
aQBkAHQAaAAAAAAAAADsAiLWhlmYQbpKDnBq3G8nBwAAANn4ImcYBrZFmz7UGX7F
i69GAGkAZwB1AHIAZQAgAG4AdQBtAGIAZQByAAAAAAAAAH4/tb5jEGtIvfasoBib
SQMAAAAALUTWHLx540ByAAAAGAXedFMAZQBhAGwAAAAAAAAAjiH2Jme5CUaGXjrF
X0PaHQcAAAB+P7W+YxBrSL32rKAYm0kDSQBkAGUAbgB0AGkAZgBpAGUAcgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAADAAAAAMAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="2fgiZxgGtkWbPtQZfsWLrw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="885"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="teR0DtTfyka+vnz4MKL5+w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Identifier" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="uqcKM/UJrEm+p/y9pC/Zfg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Location" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4410"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="SlZ4+oWcukyVTkuy8a4qKQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Collection_x002F_Accession_x0020_number" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2730"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="OXpq8nYWT0WgFrSrU1MJuw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Material" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="UU6UShKI8UKkUm5PHnaeIQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Surface" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="NGCpkVIWUUWfcgulXURp0w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Condition_x003A__x0020_fineness" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="AcJa+F3/dEOWRupa6yl8OA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Condition_x003A__x0020_completeness" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="83gqV/PGkUCzCCNBoL7ReA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Covering" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="UUIzEc+7MUWCTH+8D5v4cA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Notes" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3540"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="UI+lhqg3iUmXDofG41WKOg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MyImage" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2535"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="p7M959wRzUOw+Z/Uqk2xIA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Height" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="k1YhJd2EmU6/alWJSnkXKQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Width" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="3ftDJMcC1Ue5/LgYzP5TCA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Figure_x0020_number" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="vzvbLVHgyEO/VG4pXwTgmw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Matrix.xsd" generated="2019-05-23T09:32:04">
<Matrix>
<ID>3</ID>
<Identifier>Givry1</Identifier>
<Location>Museo del Bargello, Florence</Location>
<Collection_x002F_Accession_x0020_number>Inv. 620c</Collection_x002F_Accession_x0020_number>
<Material>bronze</Material>
<Surface>plain</Surface>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>complete</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Dated 1533-1560.  Provenance: &apos;Firenze, col.. Carrand; al Bargello dal 1888&apos; (Muzzi, Tomasello,Tori, p. 14).</Notes>
<MyImage>LonguyCDGBMmatrixA.jpg</MyImage>
<Height>119</Height>
<Width>77</Width>
<Figure_x0020_number>8</Figure_x0020_number>
</Matrix>
<Matrix>
<ID>1</ID>
<Identifier>MediciI1</Identifier>
<Location>Museo del Bargello, Florence</Location>
<Collection_x002F_Accession_x0020_number>Inv. 7</Collection_x002F_Accession_x0020_number>
<Material>bronze</Material>
<Surface>gold</Surface>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>slight damage to edge</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Dated 1517-1521.  Provenance &apos;Gargano Gargani; Firenze, Uffizi&apos; (Muzzi, Tomasello, Tori, p. 14).</Notes>
<MyImage>MediciG2BMmatrixC.jpg</MyImage>
<Height>109</Height>
<Width>70</Width>
<Figure_x0020_number>7</Figure_x0020_number>
</Matrix>
<Matrix>
<ID>4</ID>
<Identifier>Petrucci1</Identifier>
<Location>Museo del Bargello, Florence</Location>
<Collection_x002F_Accession_x0020_number>Inv. 617c</Collection_x002F_Accession_x0020_number>
<Material>bronze</Material>
<Surface>plain</Surface>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>clear</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Dated 1511-1517.  Provenance: &apos;Firenze, coll. Carrand; al Bargello dal 1888&apos; (Muzzi, Tomasello, Tori, p. 22).</Notes>
<MyImage>PetrucciA1BMmatrixA.jpg</MyImage>
<Height>113</Height>
<Width>69</Width>
<Figure_x0020_number>71</Figure_x0020_number>
</Matrix>
<Matrix>
<ID>7</ID>
<Identifier>SalviatiG2</Identifier>
<Location>Museo del Bargello, Florence</Location>
<Collection_x002F_Accession_x0020_number>Inv. 1442</Collection_x002F_Accession_x0020_number>
<Material>bronze</Material>
<Surface>plain</Surface>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>clear</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Dated 1518-1521.  Provenance: &apos;Coll. Angelo Papini, Firenze, Uffizi&apos; (Muzzi, Tomasello, Tori, p. 26).</Notes>
<MyImage>SalviatiGBMmatrixA.jpg</MyImage>
<Height>117</Height>
<Width>72</Width>
<Figure_x0020_number>79</Figure_x0020_number>
</Matrix>
<Matrix>
<ID>2</ID>
<Identifier>Valle1</Identifier>
<Location>Ashmolean Museum, Oxford</Location>
<Collection_x002F_Accession_x0020_number>Molinier, Berlin 981</Collection_x002F_Accession_x0020_number>
<Material>bronze</Material>
<Surface>gold</Surface>
<Condition_x003A__x0020_fineness>fine</Condition_x003A__x0020_fineness>
<Condition_x003A__x0020_completeness>complete</Condition_x003A__x0020_completeness>
<Covering>none</Covering>
<Notes>Bronze seal matrix.</Notes>
<MyImage>ValleAMmatrixB.jpg</MyImage>
<Height>109</Height>
<Width>72</Width>
<Figure_x0020_number>83</Figure_x0020_number>
</Matrix>
</dataroot>
