=== matthewsillence/PhD_data/Seal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Seal" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Seal">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CardinalSeal" index-key="Seal_x0020_owner " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Identifier" index-key="Identifier " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Identifier " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="SealSeal owner" index-key="Seal_x0020_owner " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAB+P7W+YxBrSL32rKAYm0kDAAAAAORwvzG4eeNAAACOAAGRXXVTAGUA
YQBsAAAAAAAAANn4ImcYBrZFmz7UGX7Fi68AAAAAGh9T7Ld540BkKl0AFAAAAE0A
YQB0AHIAaQB4AAAAAAAAALqnCjP1CaxJvqf8vaQv2X4HAAAA2fgiZxgGtkWbPtQZ
fsWLr0kAZABlAG4AdABpAGYAaQBlAHIAAAAAAAAAjiH2Jme5CUaGXjrFX0PaHQcA
AAB+P7W+YxBrSL32rKAYm0kDSQBkAGUAbgB0AGkAZgBpAGUAcgAAAAAAAAA7xHiV
otnPRJbcqLBscIM7BwAAAH4/tb5jEGtIvfasoBibSQNTAGUAYQBsACAAbwB3AG4A
ZQByAAAAAAAAABbJF7pUA3xEu0fGiZSTzokHAAAAfj+1vmMQa0i99qygGJtJA1MA
dABhAHQAdQBzAAAAAAAAAFdxA0UlslBOh/tInUoDxh4HAAAAfj+1vmMQa0i99qyg
GJtJA1QAeQBwAGUAIABvAGYAIABzAGUAYQBsAAAAAAAAABW1OP3YFz9BpQyv5S64
mFwHAAAAfj+1vmMQa0i99qygGJtJA0QAZQBzAGkAZwBuAAAAAAAAAGvhTMr3VW1L
sK0RIVOi9hQHAAAAfj+1vmMQa0i99qygGJtJA0gAZQByAGEAbABkAHIAeQAAAAAA
AABFmglmEJWCTKe0XR74KwwRBwAAAH4/tb5jEGtIvfasoBibSQNMAGUAZwBlAG4A
ZAAAAAAAAAAlHs88DgHFSLXMIyz/SNDiBwAAAH4/tb5jEGtIvfasoBibSQNTAGgA
YQBwAGUAAAAAAAAAOlSdY/WQFkej+fxeBGSz7AcAAAB+P7W+YxBrSL32rKAYm0kD
RgBhAGMAZQAAAAAAAACQGEqVNUSLT62Rlsd6R9CYBwAAAH4/tb5jEGtIvfasoBib
SQNTAGUAYQBsACAAdABpAHQAdQBsAHUAcwAAAAAAAADGtWoK8mzNQYQVgJHVrzqQ
BwAAAH4/tb5jEGtIvfasoBibSQNUAGUAcgBtAGkAbgB1AHMAIABwAG8AcwB0ACAA
cQB1AGUAbQAAAAAAAABOvqMpCnkrT44dDn3GEmkYBwAAAH4/tb5jEGtIvfasoBib
SQNSAGUAcwBlAGEAcgBjAGgAIABuAG8AdABlAHMAAAAAAAAASkxka9Q0rEqspuAn
ZoJsBAcAAAB+P7W+YxBrSL32rKAYm0kDTgBvAHQAZQBzAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAMAAAAAwAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="fj+1vmMQa0i99qygGJtJAw==
"/>
<od:tableProperty name="SubdatasheetName" type="10" value="Table.Matrix"/>
<od:tableProperty name="OrderBy" type="12" value="Seal.Identifier"/>
<od:tableProperty name="LinkChildFields" type="10" value="Identifier"/>
<od:tableProperty name="LinkMasterFields" type="10" value="Identifier"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Seal_x0020_owner" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4215"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="O8R4laLZz0SW3KiwbHCDOw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Identifier" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2895"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="jiH2Jme5CUaGXjrFX0PaHQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Status" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2580"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="FskXulQDfES7R8aJlJPOiQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Type_x0020_of_x0020_seal" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2190"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="V3EDRSWyUE6H+0idSgPGHg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Design" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4875"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="FbU4/dgXP0GlDK/lLriYXA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Heraldry" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2910"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="a+FMyvdVbUuwrREhU6L2FA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Legend" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="6135"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="RZoJZhCVgkyntF0e+CsMEQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Shape" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="JR7PPA4BxUi1zCMs/0jQ4g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Face" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="OlSdY/WQFkej+fxeBGSz7A==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Seal_x0020_titulus" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3975"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="kBhKlTVEi0+tkZbHekfQmA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Terminus_x0020_post_x0020_quem" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2130"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="xrVqCvJszUGEFYCR1a86kA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Research_x0020_notes" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="Tr6jKQp5K0+OHQ59xhJpGA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Notes" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="8745"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="Skxka9Q0rEqspuAnZoJsBA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== matthewsillence/PhD_data/Seal.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Seal.xsd" generated="2019-05-23T09:32:28">
<Seal>
<Seal_x0020_owner>Adimari, Alemanno</Seal_x0020_owner>
<Identifier>Adimarius2</Identifier>
<Status>pseudocardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>In an aedicule, a nimbed man, standing, facing half-right right, holding a palm in the right hand and a book in the left hand, (St Eusebius?); on each side, in an aedicule, a nimbed and winged figure (angel) kneeling on a pedestal, facing inwards, with hands raised, held together; in a niche below a mitred man (cardinal), facing left, looking upwards, hands raised, held together; on each side, a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Legend>S	igillm alamanni tituli sci eusebii psbricardinalis

[Sigillum Alamanni Tituli Sancti Eusebii Presbiteri Cardinalis]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>S. Eusebio</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1411</Terminus_x0020_post_x0020_quem>
<Research_x0020_notes>&apos;la croix fleuronnée brochant&apos; - Inventaire des sceaux de Champagne, A. Coulon, Volume V: Papes, Cardinaux , Archevêques , évêques 1427-1602</Research_x0020_notes>
</Seal>
<Seal>
<Seal_x0020_owner>Adimari, Alemanno</Seal_x0020_owner>
<Identifier>Adimarius3</Identifier>
<Status>pseudocardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>In an aedicule, on the left, the Virgin sitting on a bench, facing half-right, hands raised, held together; on the right, Christ sitting on a bench, facing half-left, hands raised, placing a crown on the Virgin&apos;s head; in a niche below, a mitred man (cardinal), kneeling, facing half-left, hands raised, held together; on each side a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Heraldry>Chacon col. 1086, A.1411.  McCarthy, v. 1, p. 157, &apos;Arms,- Per fess azure and or, a cross botonny gules.&apos;</Heraldry>
<Legend>Sigillm a[ . . . ]anni tituli sci eusebii ps[ . . . ] cardinalis

[Sigillum Alamanni Tituli Sancti Eusebii Presbiteri Cardinalis]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>S. Eusebio</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1411</Terminus_x0020_post_x0020_quem>
</Seal>
<Seal>
<Seal_x0020_owner>Aigrefeuille, Faydit</Seal_x0020_owner>
<Identifier>AigrefeuilleF1</Identifier>
<Status>pseudocardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>In an aedicule, a half-length Virgin and Child; below, in an aedicule, a nimbed and mitred man (St Sylvester or St Martin?), sitting on a bench, full face, his right hand raised in blessing, holding an indistinct object in his left hand; on each side in an aedicule a half-length nimbed and winged figure (angel), facing inwards, one hand raised to the chest; above; below in a niche, a mitred man (cardinal) kneeling, facing half-left, looking upwards, hands raised, held together; on each side, a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Legend>S [ . . . ] MARTINI I[ . ] 	MON . . . ] 

[Sigillum . . . Sancti Martini in Montibus]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>S. Martino ai Monti</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1383</Terminus_x0020_post_x0020_quem>
<Research_x0020_notes>&apos;trois étoiles à six rais sous un chef, à la bordure chargée de besants brochant&apos; - Inventaire des sceaux de Champagne, A. Coulon, Volume V: Papes, Cardinaux , Archevêques, évêques 1427-1602.</Research_x0020_notes>
</Seal>
<Seal>
<Seal_x0020_owner>Albergati, Nicola</Seal_x0020_owner>
<Identifier>Albergati1</Identifier>
<Status>cardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>In an aedicule, a crucifix with a crown of thorns in the centre; on each arm, a nail; a plaque above with the inscription &apos;INRI&apos;; below, a nail at the base; below, in a niche, a man (cardinal), kneeling, facing right, hands raised, holding a book; on the left, a cardinal&apos;s hat with tasseled cords.</Design>
<Legend>S · NIChOLAI · TIT · CRVCI&apos; · Ī · IhERVSAL&apos; · PRESBITERI · CARDINALIS

[Sigillum Nicholai tituli Cruci in Iherusaleme Presbiteri Cardinalis]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>Sta. Croce in Gerusalemme</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1426</Terminus_x0020_post_x0020_quem>
<Research_x0020_notes>Seal is unusual because the cardinal&apos;s hat is behind the kneeling cardinal, who appears to be praying in a niche between two spiral columns.  The foliate motifs on the ogival arch above seem to be Venetian.  Significantly there is no heraldry present.</Research_x0020_notes>
</Seal>
<Seal>
<Seal_x0020_owner>Albret, Louis d&apos;</Seal_x0020_owner>
<Identifier>AlbretL1</Identifier>
<Status>cardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>In the spandrels on each side of a canopy, a half-length winged figure (angel); below, on the left, in an aedicule, a nimbed man standing, full face, holding indistinct objects in both hands; on the right, in an aedicule, a nimbed man, standing, full face, holding a palm in the right hand and an indistinct object in the left hand; below, in an aedicule, a Virgin and Child, standing, full face; on the left, in a niche, a nimbed man (St John the Baptist), wearing a hair coat, holding a lamb in the left hand; on the right, in a niche, a nimbed man, standing, holding a palm leaf in the right hand and an indistinct object in the left hand; below, in a niche, a mitred man (cardinal), kneeling, facing half-left, looking upwards, hands raised, held together; on each side, a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Heraldry>Chacon col. 1214, A.1461.</Heraldry>
<Legend>S · D · L · TT · STOM · PETRI &amp; MARCELLINI · PBRI · CARDINALIS · DE · LEBRE . . . 

[Sigillum Domini Ludovici Tituli Sanctorum Petri et Marcellini Presbiteri Cardinalis de Lebreto]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>SS. Marcellino e Pietro</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1461</Terminus_x0020_post_x0020_quem>
</Seal>
<Seal>
<Seal_x0020_owner>Amboise, Georges d&apos;</Seal_x0020_owner>
<Identifier>Amboise1</Identifier>
<Status>cardinal priest</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>Below a canopy, on the left, the Virgin sitting, full face, holding the dead Christ, sitting, facing half-right; on the right a man (cardinal), kneeling, facing left, hands raised, held together; behind, on the right, a man (St John the Baptist), standing, full face, holding a lamb in the right hand; below, on the left a shield of arms surmounted by a cross; on the right a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Heraldry>Two lions passant guardant in pale for Archiepiscopal Province of Rouen (left); paly of six, Amboise, ensigned with an archbishop&apos;s cross and cardinal&apos;s hat (right).
Chacon col. 1334, A.1500.  
McCarthy, v.1, p. 211, &apos;Arms,- Paly of six gules and or.&apos;</Heraldry>
<Legend>SIGILLVM · GEORGII · CARDINALIS : DE AMBASIA · ROTHOM · ARCHIEPI.

[Sigillum Georgii Cardinalis de Ambasia Rothomagensis Archiepiscopi]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>S. Sisto</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1498</Terminus_x0020_post_x0020_quem>
<Notes>&apos;Rouen&apos;.  Horizontal lines above &apos;M&apos; in &apos;ROTHOM&apos; and &apos;P&apos; in &apos;ARCHIEPI&apos; in legend.  N.B. that the canopy is unusual at this date; the rib-vaulting is also shown.  There is no exergue: the shields float on the picture plane.  The border is quite wide.

Demay, G. &apos;Inventaire des Sceaux de la Normandie&apos;, no. 2156, p. 232.  Original held in Musée de Rouen.  &apos;Sceau détaché&apos;.

Alternative measurements: 85 x 65</Notes>
</Seal>
<Seal>
<Seal_x0020_owner>Aragona, Giovanni d&apos;</Seal_x0020_owner>
<Identifier>AragonJ1</Identifier>
<Status>cardinal deacon</Status>
<Type_x0020_of_x0020_seal>seal of dignity</Type_x0020_of_x0020_seal>
<Design>On a throne, the Virgin and Child sitting; on the left, a nimbed man standing, facing half-right; on the right, a nimbed man standing, facing half-left, looking upwards, arms held behind the back; below, a shield of arms surmounted by a cardinal&apos;s hat.</Design>
<Heraldry>Shield quartered: 1 and 4 Aragon, 2 and 3, three bundles, three birds in pale, cross of Jerusalem.

McCarthy, v.1, p. 198, &apos;Arms,- ARAGON quartering per pale HUNGARY, ANJOU Ancient and JEUSALEM [sic].&apos; [Or, four pallets gules quartering per pale Barry gules and argent impaling gules, from a triple mount vert, a patriarchal cross argent issuing from a coronet or, France ancient, a label of four points gules (often shown when quartered as three points) and Argent, a cross potent between four crosslets or].</Heraldry>
<Legend>SIGILLVM [ . . . ] IOANNIS · CARDINALIS [ . . . ] ARAGONIA

[Sigillum . . . Johannis Cardinalis . . . Aragonia]</Legend>
<Shape>pointed oval</Shape>
<Face>obverse</Face>
<Seal_x0020_titulus>S. Adriano</Seal_x0020_titulus>
<Terminus_x0020_post_x0020_quem>1477</Terminus_x0020_post_x0020_quem>
<Research_x0020_notes>Enthroned Madonna and Child design is unusual in use of three projecting circular bases for each saint.  Early use of asymmetrical balusters?  Narrow band for legend.</Research_x0020_notes>
</Seal>
<Seal>
<Seal_x0020_owner>Barbo, Marco</Seal_x0020_owner>
